import {createFileRoute} from '@tanstack/react-router'
import {useState} from 'react'
import {Search} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {PageHeading,ContactBanner} from '@/components/aura-site'
import {images,pageHead} from '@/lib/aura-data'
const materials=[{name:'Warm Walnut',category:'Wood',image:images.dining,description:'Rich grain · Warm finish'},{name:'Dark Emperador',category:'Stone',image:images.darkRoom,description:'Expressive veining · Polished finish'},{name:'Natural Linen',category:'Textiles',image:images.bedroom,description:'Soft hand · Natural weave'},{name:'Ivory Travertine',category:'Stone',image:images.living,description:'Organic texture · Honed finish'},{name:'Bouclé',category:'Textiles',image:images.living,description:'Sculptural softness · Cream tone'},{name:'Natural Oak',category:'Wood',image:images.dining,description:'Gentle grain · Matte finish'}]
export const Route=createFileRoute('/materials')({head:()=>pageHead('Material Library','Discover a curated, static library of natural woods, stone and tactile textiles for interior inspiration.','/materials'),component:Materials})
function Materials(){const [category,setCategory]=useState('All');const [query,setQuery]=useState('');const filtered=materials.filter(m=>(category==='All'||m.category===category)&&m.name.toLowerCase().includes(query.toLowerCase()));return <main><PageHeading label="Material library" title="Beauty you can feel." description="A curated palette of wood, stone and textiles. Illustrative applications, chosen for their character and enduring appeal."/><section className="wrap pb-20"><div className="filters">{['All','Wood','Stone','Textiles'].map(c=><Button key={c} variant={category===c?'default':'filter'} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</Button>)}<label className="search-field"><Search/><input aria-label="Search materials" value={query} placeholder="Search materials" onChange={e=>setQuery(e.target.value)}/></label></div>{filtered.length?<div className="material-grid">{filtered.map(m=><div key={m.name} className={`material-card ${m.category.toLowerCase()}`}><div className="image-frame"><img src={m.image} alt={`${m.name} interior application`} width={1536} height={1024} loading="lazy"/></div><h3>{m.name}</h3><p>{m.description}</p></div>)}</div>:<p className="empty-state">No materials match this selection.</p>}</section><ContactBanner/></main>}
