import { Link, useRouterState } from '@tanstack/react-router'
import { useState } from 'react'
import { ArrowUpRight, ArrowRight, Menu, X, ArrowLeft, Leaf, House, Building2, Layers, Check, SlidersHorizontal } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { images, projects } from '@/lib/aura-data'
export function Brand(){return <Link to="/" className="brand" aria-label="AuraNest home"><svg className="brand-mark" viewBox="0 0 44 44" fill="none" stroke="currentColor" strokeWidth="1"><path d="M3 38 22 4l19 34M10 38 22 16l12 22M15 30h14M7 38h30M22 4v34"/></svg><span className="brand-name">AuraNest<small>Interiors</small></span></Link>}
export function SiteHeader(){const path=useRouterState({select:s=>s.location.pathname});const [open,setOpen]=useState(false);return <header className={`site-header ${path==='/'?'':'interior'}`}><div className="wrap header-inner"><Brand/><nav aria-label="Main navigation" className={`nav-links ${open?'open':''}`}>{([['/','Home'],['/about','About'],['/services','Services'],['/projects','Projects'],['/studio','Design Studio'],['/blog','Journal']] as const).map(([to,label])=><Link key={to} to={to} activeOptions={{exact:true}} activeProps={{className:'active'}} onClick={()=>setOpen(false)}>{label}</Link>)}</nav><Button variant={path==='/'?'hero':'studio'} asChild className="header-cta"><Link to="/contact">Book a consultation <ArrowUpRight/></Link></Button><Button className="mobile-menu-button" variant="ghost" size="icon" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></header>}
export function SiteFooter(){return <footer className="site-footer"><div className="wrap"><div className="footer-top"><div><Brand/><p className="body-copy mt-5 text-xs">Thoughtfully designed. Beautifully lived.</p></div><div className="footer-links"><Link to="/about">Our studio</Link><Link to="/projects">Our work</Link><Link to="/materials">Materials</Link><Link to="/contact">Let’s talk <ArrowUpRight className="inline size-3"/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} AuraNest Interiors. All rights reserved.</span><span>Bangalore, India · A concept design studio</span></div></div></footer>}
export function PageHeading({label,title,description}:{label:string;title:string;description?:string}){return <div className="page-heading wrap fade-in"><p className="eyebrow">{label}</p><h1>{title}</h1>{description&&<p>{description}</p>}</div>}
export function TextLink({to,children}:{to:'/'|'/about'|'/services'|'/projects'|'/studio'|'/contact'|'/materials'|'/blog';children:React.ReactNode}){return <Link to={to} className="text-link">{children}<ArrowUpRight/></Link>}
export function ProjectCard({project}:{project:typeof projects[number]}){return <Link className="project-card" to="/projects/$slug" params={{slug:project.slug}}><div className="image-frame"><img src={project.image} alt={`${project.name} interior`} width={1536} height={1024} loading="lazy"/><span className="project-type">{project.style}</span></div><div className="project-info"><div><h3>{project.name}</h3><p>{project.city} <span className="mx-2">·</span> {project.area}</p></div><ArrowUpRight/></div></Link>}
export function AboutSection(){return <section className="section"><div className="wrap about-grid"><div className="about-images"><img src={images.dining} alt="Natural wood dining space with garden views" width={1536} height={1024} loading="lazy"/><img src={images.bedroom} alt="Thoughtfully layered linen and warm wood bedroom" width={1536} height={1024} loading="lazy"/></div><div className="about-copy"><p className="eyebrow">The AuraNest philosophy</p><h2 className="section-title">Not just a space.<br/>A feeling of <em>home.</em></h2><p className="body-copy">We believe the most beautiful spaces are the ones that feel like you. A thoughtful balance of timeless design, natural materials, and the little details that make life extraordinary.</p><TextLink to="/about">Discover our story</TextLink><div className="stats"><div className="stat"><strong>12+</strong><span>Years of inspiration</span></div><div className="stat"><strong>150+</strong><span>Spaces imagined</span></div><div className="stat"><strong>8</strong><span>Cities, one vision</span></div></div></div></div></section>}
export const services=[{name:'Residential Interiors',icon:House,description:'From city apartments to expansive villas, homes that reflect your individuality and embrace everyday life.'},{name:'Commercial Spaces',icon:Building2,description:'Purposeful workspaces, welcoming hospitality and distinctive retail experiences that bring your brand to life.'},{name:'Turnkey & Renovation',icon:Layers,description:'One considered vision, from the first sketch to the finishing touch. Seamless transformations, beautifully delivered.'}]
export function ServicesSection(){return <section className="section inverse"><div className="wrap"><div className="section-top"><div><p className="eyebrow">What we do</p><h2 className="section-title">Your vision. Our craft.</h2></div><TextLink to="/services">Explore our services</TextLink></div><div className="service-grid">{services.map(s=><div className="service-item" key={s.name}><s.icon strokeWidth={1}/><h3>{s.name}</h3><p>{s.description}</p><TextLink to="/contact">Let’s create together</TextLink></div>)}</div></div></section>}
const quotes=[{quote:'They didn’t just design our home. They understood how we wanted to live — and made every corner feel like us.',name:'Ananya & Rohan',city:'The Ivory Residence, Bangalore'},{quote:'Every texture, every detail, every moment of light feels intentional. Our home has become our favourite place.',name:'Meera & Arjun',city:'Casa Verde, Mumbai'},{quote:'The transformation feels effortless. A warm, personal space that works as beautifully as it looks.',name:'Priya S.',city:'The Noir Apartment, Hyderabad'}]
export function Testimonials(){const [index,setIndex]=useState(0);const quote=quotes[index];if(!quote)return null;return <section className="section quote-section"><div className="wrap"><p className="eyebrow">Words from our clients · Sample stories</p><span className="text-primary font-display text-5xl">“</span><blockquote aria-live="polite">{quote.quote}</blockquote><div className="quote-name">{quote.name}<small>{quote.city}</small></div><div className="quote-controls"><Button variant="ghost" size="icon" aria-label="Previous testimonial" onClick={()=>setIndex((index+2)%3)}><ArrowLeft/></Button><span className="text-xs text-muted-foreground">0{index+1} / 03</span><Button variant="ghost" size="icon" aria-label="Next testimonial" onClick={()=>setIndex((index+1)%3)}><ArrowRight/></Button></div></div></section>}
export function ContactBanner(){return <section className="section contact-banner"><div className="wrap"><div><p className="eyebrow">A beautiful beginning</p><h2>Let’s make room<br/>for <em>your story.</em></h2></div><Button variant="studio" asChild><Link to="/contact">Start a conversation <ArrowUpRight/></Link></Button></div></section>}
export function Hero(){return <><section className="hero"><img className="hero-image" src={images.living} width={1920} height={1088} alt="AuraNest-inspired double-height living room with sculptural furniture and natural light" fetchPriority="high"/><div className="wrap hero-content fade-in"><p className="eyebrow">AuraNest Interiors · Thoughtful spaces, timeless living</p><h1>Spaces designed<br/>for the way<br/>you <em>live.</em></h1><p>Beautiful interiors. Meaningful details.<br/>A home that feels unmistakably yours.</p><div className="hero-actions"><Button variant="studio" asChild><Link to="/projects">Explore our work <ArrowUpRight/></Link></Button><Button variant="hero" asChild><Link to="/contact">Let’s talk <ArrowUpRight/></Link></Button></div></div><div className="wrap hero-bottom"><span className="scroll-down">Scroll to discover <ArrowRight className="size-3 rotate-90"/></span><span className="hero-location">Bangalore · Designing across India</span><span className="hero-count">01 <span/> 04</span></div></section><div className="intro-band"><div className="wrap"><p>Considered design. Lasting impressions.</p><div className="intro-values"><span><Leaf/>Thoughtful by nature</span><span><Check/>Crafted with care</span><span><SlidersHorizontal/>Uniquely yours</span></div></div></div></>}
